apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  project: udf
  source:
    chart: nginx-ingress
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://helm.nginx.com/stable
    targetRevision: 0.13.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
