grafana:
  service:
    type: NodePort
    nodePort: 32517
nginx-ingress:
  controller:
    enableSnippets: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
  prometheus:
    create: true
  serviceInsight:
    create: true
prometheus:
  pushgateway:
    enabled: false
